config/routes.rb
Rails.application.routes.draw do
  root 'root#index'

  resources :users, only: [:new, :create, :destroy]
  resources :links, only: [:index, :create, :edit, :update]
  resources :sessions, only: [:new, :create]

  namespace :api, :defaults => {format: :json }do
    namespace :v1 do
      resources :links, only: [:update, :index]
    end
  end
end

app/models/link.rb
require 'uri'
class Link < ActiveRecord::Base
  before_save :url_valid?
  validates :title, presence: true
  validates :url, presence: true
  belongs_to :user

  def url_valid?
    url = self.url
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
    false
  end

  def status_output
    self.status ? 'Read' : 'Unread' 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true,
                    uniqueness: true
  validates :password, presence: true
  has_many :links
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < Api::ApiController
  respond_to :json

  def index
    respond_with Link.where(user_id: current_user.id)
  end

  def update
    link = Link.find(params[:id])
    respond_with link.update(link_params)
  end

  private

  def link_params
    params.require(:data).permit(:title, :url, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @link = Link.new
    @links = Link.where(user_id: current_user.id)
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    @link.update(link_params)
    if @link.save
      redirect_to links_path
    else
      flash.now[:error] = "Please put in a valid URL! Tip: Url must start with http://(...)"
      render :edit
    end
  end

  def create
    @link = current_user.links.new(link_params)
    if @link.save
      redirect_to links_path
    else
      flash.now[:error] = "Please put in a valid URL! Tip: Url must start with http://(...)"
      @links = Link.where(user_id: current_user.id)
      render :index
    end
  end

  private

  def link_params
    params.require(:link).permit(:title, :url)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    if current_user
      redirect_to links_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email])

    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      flash.now[:success] = "Welcome Home #{user.name}!"
      redirect_to links_path
    else
      flash.now[:error] = "Sorry wrong information!"
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.name}!"
      redirect_to links_path
    else
      render :new
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash_#{type}" %>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<%= form_for @link, method: :put do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit 'Update' %>
<% end %>

app/views/links/index.html.erb
<%= link_to 'Sign Out', user_path(current_user.id), method: :DELETE  %>
<br>
<br>
<%= form_for @link do |f| %>
  <%= f.text_field :title, placeholder: 'Title' %>
  <%= f.text_field :url, placeholder: 'Url' %>
  <%= f.submit 'Create Link' %>
<% end %>
<br>
<br>
<%= text_field_tag :search, nil, placeholder: 'Search' %>

<div class='links'>
  <% @links.each do |link| %>
    <div class='link' id="<%= link.id %>">
      <h3 class='content'><%= link.title %></h3>
      <ul>
        <li class="<%= link.status_output %>">
          <a class='content' href='<%= link.url %>'><%= link.url %></a> -
          <button class='content'>Mark as <%= link.status_output %></button>
        </li>
        <li><a href='/links/<%= link.id %>/edit'>Edit</a></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/root/index.html.erb
Welcome to the ThoughtBox:
Where dreams come to life:0

<%= link_to 'Sign Up', new_user_path %>

<%= link_to 'Sign In', new_session_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <h4> <%=  pluralize(@user.errors.count, "error") %> prohibited this record from being saved: </h4>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><strong class="error"> <%= message %> </strong> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f|  %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit 'Create' %>
<% end %>